### ISSUE TITLE
SDL Controller not working in Mupen64Plus

### ISSUE THREAD

**Issue by TheDJ42** [ToadKing/wii-u-gc-adapter#10]
So while using Mupen64 I have added the controller to the list of SDL game controllers, however when I open up the emulator I get no response from the controller. Intrestingly enough rumble works if I press the comma key or the peirod key on my keyboard. I get the following input messages from the emulator:
UI-Console: using Input plugin: 'Mupen64Plus SDL Input Plugin' v2.0.0
Input Warning: parsing error in key() parameter of button 'DPad R' for controller 1
Input Warning: parsing error in key() parameter of button 'DPad L' for controller 1
Input Warning: parsing error in key() parameter of button 'DPad D' for controller 1
Input Warning: parsing error in key() parameter of button 'DPad U' for controller 1
Input Warning: parsing error in key() parameter of button 'Start' for controller 1
Input Warning: parsing error in key() parameter of button 'B Button' for controller 1
Input Warning: parsing error in key() parameter of button 'A Button' for controller 1
Input: N64 Controller #1: Using auto-config with SDL joystick 0 ('Wii U GameCube Adapter Port 1')
Input: 1 controller(s) found, 1 plugged in and usable in the emulator
Input: Rumble activated on N64 joystick #1
Input Warning: Couldn't open rumble support for joystick #2
Input Warning: Couldn't open rumble support for joystick #3
Input Warning: Couldn't open rumble support for joystick #4
Input: Mupen64Plus SDL Input Plugin version 2.0.0 initialized.
I have tried this with a few different games and I get the same result. Help is appreciated, Thanks.

**Comment by ToadKing** [comment]
That looks like your mupen64 config file has formatting errors.

**Comment by TheDJ42** [comment]
What kind of formatting errors are we talking about?

**Comment by ToadKing** [comment]
It's an error with your mupen64plus configuration file, most likely nothing to do with wii-u-gc-adapter itself.
