### ISSUE TITLE
Adapter cannot be found

### ISSUE THREAD

**Issue by johan-bjareholt** [ToadKing/wii-u-gc-adapter#11]
I added this package to the Arch User Repository a few weeks ago and it has been working very well on my laptop. Now when i'm trying it on my desktop it doesn't work though which is strange. The C code simply outputs "uinput creation failed" and the python script outputs

     File ./gcscript.py, line 156, in main
       dev.ctrl_transfer(0x21, 11, 0x0001, 0, [])
     File /usr/lib/python3.4/site-packages/usb/core.py, line 971, in ctrl_transfer
       self.__get_timeout(timeout))
     File /usr/lib/python3.4/site-packages/usb/backend/libusb1.py, line 819, in ctrl_transfer
       timeout))
     File /usr/lib/python3.4/site-packages/usb/backend/libusb1.py, line 552, in _check
       raise USBError(_strerror(ret), ret, _libusb_errno[ret])
    usb.core.USBError: [Errno 32] Pipe error

I tried it with python2 aswell with the same error

What is wierd though is that it works perfectly fine in dolphin when running it as root, so i guess that it isn't a driver or hardware issue.

Looking in the C code it doesn't give much help since udev_device_new_from_subsystem_sysname(udev, "misc", "uinput"); only returns NULL which means that libudev cannot find the device, but it would be a pain to debug why libudev can't find it.

My libudev is built in to libsystemd package and my libusb at version 1.0.19, the whole system is simply a up-to-date arch install, and yes i am running both the C program and the python script as superuser.

Does anyone have any clues why it isn't working? Would be nice to be able to use the controllers with other games than dolphin.

**Comment by ToadKing** [comment]
The uinput module might not be loaded on your system, try modprobe uinput

**Comment by johan-bjareholt** [comment]
Thanks alot, worked instantly!

You should probably add that to the README.
