### ISSUE TITLE
Warning: writing input events failed

### ISSUE THREAD

**Issue by bobbysq** [ToadKing/wii-u-gc-adapter#23]
When I run the script, I get this warning whenever I move a stick or press a button. The input appears to update, but do so slowly. I'm running as root.

Setup:

* Ubuntu Trusty x64 on Asus c300
* Mayflash GC adapter on Wii U mode
* SSB Gamecube Controller

**Comment by nvitaterna** [comment]
I'm getting the same thing on my XU4 running debian with the official adapter.

**Comment by Emill** [comment]
Hi. Could you test my patch at https://github.com/ToadKing/wii-u-gc-adapter/pull/25?
