### ISSUE TITLE
What do I run?

### ISSUE THREAD

**Issue by aaronfranke** [ToadKing/wii-u-gc-adapter#30]
"Usage

Simply run the program."

What command is it? I tried:

    $ wii-u-gc-adapter
    wii-u-gc-adapter: command not found

**Comment by WinSuk** [comment]
To run something from the directory you're currently in, you have to use:

`./`

So as long as you are in the folder, it would be:

`./wii-u-gc-adapter`

**Comment by aaronfranke** [comment]
Do I have to run this every time I want to use my adapter? There's no installation or adding to kernel?

**Comment by WinSuk** [comment]
It's not a kernel driver or anything like that, it's just a userspace program that accesses the USB device.

Starting things on boot depends on your distro/preferences. For Ubuntu, this should work: https://help.ubuntu.com/stable/ubuntu-help/startup-applications.html

Also depending on your distro, there may be an unofficial package that comes with a startup file that can be enabled easily. (the Arch AUR package has this for example)

**Comment by aaronfranke** [comment]
Alrighty then. Maybe this is too much to ask, but it would be really cool if you merged this driver into the Linux kernel or something. Consider this a wishlist item.

**Comment by ToadKing** [comment]
This is a userspace program. It can't be merged into the Linux kernel.
