### ISSUE TITLE
Not working with steam

### ISSUE THREAD

**Issue by ellliottt** [ToadKing/wii-u-gc-adapter#40]
My adapter is detected and connects fine, and it shows up here https://html5gamepad.com/. But steam big picture doesnt detect any controllers. Is there a fix for this?

**Comment by Virusmater** [comment]
This is quite an uncommon gamepad to use with Steam. Has no button to bring steam menu (like a home button of Nintendo Wii U Pro controller), has no 2nd shoulder button. Best way to go - use xboxdrv
