### ISSUE TITLE
Missing time.h

### ISSUE THREAD

**Issue by dustinf1989** [ToadKing/wii-u-gc-adapter#52]
I've installed the prerequisites, and when I run make in the terminal, I get this error, which seems to want a time.h file which is missing:

cc -c -o wii-u-gc-adapter.o wii-u-gc-adapter.c -Wall -Wextra -pedantic -Wno-format -std=c99 -I/usr/include/libusb-1.0  -O2
wii-u-gc-adapter.c:5:10: fatal error: time.h: No such file or directory
 #include <time.h>
          ^~~~~~~~
compilation terminated.
Makefile:16: recipe for target 'wii-u-gc-adapter.o' failed
make: *** [wii-u-gc-adapter.o] Error 1

**Comment by ToadKing** [comment]
`time.h` is a part of the C standard library. If that's missing from your system then some important build packages are missing from your system.

What distro are you using?

**Comment by dustinf1989** [comment]
Thanks, I didn't know what I was looking for before but I used these commands to get the file and got it working.

```
sudo apt-get update 
sudo apt-get install build-essential
```
