### ISSUE TITLE
Syntax error on execution   

### ISSUE THREAD

**Issue by emini** [ToadKing/wii-u-gc-adapter#9]
wii-u-gc-adapter: 1: wii-u-gc-adapter: Syntax error: "(" unexpected

Xubuntu 14.04.1
Packages used: libudev-dev 204-5ubuntu20, libusb-1.0-0-dev 2:1.0.17-ubuntu

**Comment by TheDJ42** [comment]
I think this article may have some insight. http://unix.stackexchange.com/questions/45781/shell-script-fails-syntax-error-unexpected I am also have this syntax error.

**Comment by ToadKing** [comment]
The driver is not a shell script

**Comment by TheDJ42** [comment]
Then I have no idea why I'm getting this. Running it as root finally works though.

**Comment by TheDJ42** [comment]
So after working through it, I figured it out. The command that emini is running is probably "sudo sh wii-u-controller-adapter" which is incorrect, the command that you should be running is "(sudo) ./wii-u-controller-adapter" (in the directory that the program is in of course."
